version: '3.9'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: svaudio_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "8080:8080"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: svaudio_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: svaudio_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    image: svaudio_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat.sh

  flower:
    <<: *django
    image: svaudio_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower.sh

  node:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    image: svaudio_node
    container_name: node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
